// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edcsxmamqogsmfmzyzll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkY3N4bWFtcW9nc21mbXp5emxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzQxMTMsImV4cCI6MjA2MTAxMDExM30.w_DBj7rKCco0u3eFEmc8_A7qbPl_C6axVLN_1j_vdMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);